//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MealMonkey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MM_Orders
    {
        public int OrderDetailsid { get; set; }
        public string OrderNo { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Status { get; set; }
        public Nullable<int> PaymentId { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        //public Nullable<decimal> Amount { get; set; }
    }
}
